### PR TITLE
docs: update ng test command

### PR DESCRIPTION
**Pull request by alan-agius4**
Related to: https://github.com/angular/angular-cli/issues/13154

### CODE REVIEW

**Comment by WtfJoke** [comment]
I opened #175 and were happy that you might have provided the solution, but I still have the same problem of unverified breakpoints. But maybe im an exception.

**Comment by alan-agius4** [comment]
@WtfJoke, it does. I'll update it.

**Comment by auchenberg** [comment]
LGTM. Thanks @alan-agius4

**Comment by mfcallahan** [comment]
Also experiencing this issue.  I read through issue #175 and this one but when the debugger starts and tests run, all breakpoints are showing as unverified.

**Pull request merged**
