### PR TITLE
passing arguments with variables inline fails

### PR DESCRIPTION
**Pull request by janat08**
https://github.com/Microsoft/vscode/issues/43522

### CODE REVIEW

**Comment by auchenberg** [comment]
Looks like `args` is already a part of the config? Is your intent to replace the args?

**Comment by janat08** [comment]
or that issue could be reopened, and everything just concatenated and split.

**Comment by auchenberg** [comment]
@janat08 I prefer if we have our examples working out of the box, so maybe we could add a jest config that's used in the launch.json?

**Comment by janat08** [comment]
made another PR

**Pull request closed without merging**
